export enum TABLES {
  OTP = 'otps',
  USER = 'users',
  DIVISIONS = 'divisions',
  STATIONS = 'stations',
  MANAGERS = 'managers',
  ROLES = 'roles',
  APARTMENTS = 'apartments',
  COLONIES = 'colonies',
  EMPLOYEES = 'employees',
  EMPLOYEE_VERIFICATIONS = 'employee_verifications',
  APPLICATIONS = 'applications',
  APPLICATION_PRIORITIES = 'application_priorities',
  OCCUPATIONS = 'occupations',
  APARTMENT_HISTORY = 'apartment_history',
  EMPLOYEE_HISTORY = 'employee_history',
  VACANCY_REQUESTS = 'vacancy_requests',
  TRANSFER_REQUESTS = 'transfer_requests',
}
